//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (If yes, answer question 44c).
        /// </summary>
        internal static string answer44c {
            get {
                return ResourceManager.GetString("answer44c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By whom do?.
        /// </summary>
        internal static string ByWhomDo {
            get {
                return ResourceManager.GetString("ByWhomDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. After the catastrophe, is food production of the community affected?.
        /// </summary>
        internal static string food1 {
            get {
                return ResourceManager.GetString("food1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Assuming customer demand doubles, do you have enough goods to sell?.
        /// </summary>
        internal static string food10 {
            get {
                return ResourceManager.GetString("food10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Have you ever had enough goods to sell?.
        /// </summary>
        internal static string food11 {
            get {
                return ResourceManager.GetString("food11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Are the people&apos;s food reserves damaged?.
        /// </summary>
        internal static string food2 {
            get {
                return ResourceManager.GetString("food2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. What have affected people done to cope with this damage?.
        /// </summary>
        internal static string food3 {
            get {
                return ResourceManager.GetString("food3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Has there been food intervention?.
        /// </summary>
        internal static string food4 {
            get {
                return ResourceManager.GetString("food4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. What are the impacts of affected people&apos;s income?.
        /// </summary>
        internal static string food5 {
            get {
                return ResourceManager.GetString("food5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Do people now have access to food markets / shops?.
        /// </summary>
        internal static string food6 {
            get {
                return ResourceManager.GetString("food6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. On average, how long does it take people (in minutes) to reach the market / store?.
        /// </summary>
        internal static string food7 {
            get {
                return ResourceManager.GetString("food7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. After the storm, the price of food staples (rice) fluctuate?
        ///                         (number 48 - 50 used to interview traders in the nearest area).
        /// </summary>
        internal static string food8 {
            get {
                return ResourceManager.GetString("food8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Currently, rice is available in the local market? (mark &apos;v&apos; in the appropriate box).
        /// </summary>
        internal static string food9 {
            get {
                return ResourceManager.GetString("food9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. After the disaster, is the affected community affected by health?.
        /// </summary>
        internal static string health1 {
            get {
                return ResourceManager.GetString("health1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Are there any communicable diseases that result from the disaster?.
        /// </summary>
        internal static string health2 {
            get {
                return ResourceManager.GetString("health2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Do people have to pay for medicine / hospital fees?.
        /// </summary>
        internal static string health3 {
            get {
                return ResourceManager.GetString("health3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. What are the types of local housing?.
        /// </summary>
        internal static string home1 {
            get {
                return ResourceManager.GetString("home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Who is affected household utensils to use?.
        /// </summary>
        internal static string home10 {
            get {
                return ResourceManager.GetString("home10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Has there been or will there be any interference with household tools / utensils?.
        /// </summary>
        internal static string home11 {
            get {
                return ResourceManager.GetString("home11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. What is the structure of the house popular in the community?.
        /// </summary>
        internal static string home2 {
            get {
                return ResourceManager.GetString("home2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Damage to the house after the storm (only damage to the main house)..
        /// </summary>
        internal static string home3 {
            get {
                return ResourceManager.GetString("home3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The home must have been occupied for at least the last 6 months and during a disaster. House speed: 50% of the main roof.
        /// </summary>
        internal static string home3des {
            get {
                return ResourceManager.GetString("home3des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. How did people respond to house damage (tick &apos;v&apos; in the appropriate boxes).
        /// </summary>
        internal static string home4 {
            get {
                return ResourceManager.GetString("home4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Are construction materials (including tarpaulins ...) available locally? (mark &apos;X&apos; in the appropriate box).
        /// </summary>
        internal static string home5 {
            get {
                return ResourceManager.GetString("home5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. After the storm, prices of building materials increased?.
        /// </summary>
        internal static string home6 {
            get {
                return ResourceManager.GetString("home6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Has there been or will be housing related interventions?.
        /// </summary>
        internal static string home7 {
            get {
                return ResourceManager.GetString("home7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Are people affected by household items (blankets, curtains, cooking utensils)?.
        /// </summary>
        internal static string home8 {
            get {
                return ResourceManager.GetString("home8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. How have affected people responded?.
        /// </summary>
        internal static string home9 {
            get {
                return ResourceManager.GetString("home9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Total number of villages in the commune.
        /// </summary>
        internal static string info1 {
            get {
                return ResourceManager.GetString("info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Total number of deaths due to disaster.
        /// </summary>
        internal static string info11 {
            get {
                return ResourceManager.GetString("info11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Total number of people injured by disaster.
        /// </summary>
        internal static string info12 {
            get {
                return ResourceManager.GetString("info12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13. Among the poor and near poor households affected by the disaster, how many households have the following objects:.
        /// </summary>
        internal static string info13 {
            get {
                return ResourceManager.GetString("info13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a. Women who are pregnant or breastfeeding.
        /// </summary>
        internal static string info13a {
            get {
                return ResourceManager.GetString("info13a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b. Children under 5 years old.
        /// </summary>
        internal static string info13b {
            get {
                return ResourceManager.GetString("info13b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c. Important is the main labor in the household (the person who feeds the family).
        /// </summary>
        internal static string info13c {
            get {
                return ResourceManager.GetString("info13c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d. People with disabilities and people with chronic diseases.
        /// </summary>
        internal static string info13d {
            get {
                return ResourceManager.GetString("info13d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14. Socio-cultural characteristics of the locality:.
        /// </summary>
        internal static string info14 {
            get {
                return ResourceManager.GetString("info14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Percentage of ethnic minority people.
        /// </summary>
        internal static string info14a {
            get {
                return ResourceManager.GetString("info14a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Percentage of people who can read and write.
        /// </summary>
        internal static string info14b {
            get {
                return ResourceManager.GetString("info14b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15. What are the vulnerabilities (pre-disaster)?.
        /// </summary>
        internal static string info15 {
            get {
                return ResourceManager.GetString("info15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16. The main types of livelihoods in the locality (tick the appropriate box):.
        /// </summary>
        internal static string info16 {
            get {
                return ResourceManager.GetString("info16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a. Agriculture (rice, crops).
        /// </summary>
        internal static string info16a {
            get {
                return ResourceManager.GetString("info16a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Total number of households in the commune.
        /// </summary>
        internal static string info2 {
            get {
                return ResourceManager.GetString("info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Total population.
        /// </summary>
        internal static string info3 {
            get {
                return ResourceManager.GetString("info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Of which the total number of women.
        /// </summary>
        internal static string info4 {
            get {
                return ResourceManager.GetString("info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Total poor households.
        /// </summary>
        internal static string info5 {
            get {
                return ResourceManager.GetString("info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Total near poor households.
        /// </summary>
        internal static string info6 {
            get {
                return ResourceManager.GetString("info6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Total number of villages damaged.
        /// </summary>
        internal static string info7 {
            get {
                return ResourceManager.GetString("info7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Total number of damaged households in general.
        /// </summary>
        internal static string info8 {
            get {
                return ResourceManager.GetString("info8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Total poor households damaged.
        /// </summary>
        internal static string info9 {
            get {
                return ResourceManager.GetString("info9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify interventions?.
        /// </summary>
        internal static string SpecifyInterventions {
            get {
                return ResourceManager.GetString("SpecifyInterventions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d. Aquaculture (including fishing).
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18. Response activities have been or will take place in the locality?.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the activity?.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By whom?.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19. What is the security situation of the locality, is there anything to worry about?.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. After the disaster, do people have enough clean water (food and drink)?.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. How many people use water per day?.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. At what time do people&apos;s water come from? (Mark &apos;v&apos; in the appropriate boxes).
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well with cover, wells.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine water.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain water.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b. forestry.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (specify).
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water in rivers, lakes, ponds, dams.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Is the water at risk of microbial or chemical contamination?.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If yes, indicate the risk.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. What water source can be used to provide enough for affected people?.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a. Clear water source.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b. Specify the measures needed to treat the water source.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Do people have safe water containers?.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. How far do people have to go in meters to get water?.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Was there any water support available?.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e. Renting.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What support / supported objects.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting units.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (If yes, specify).
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. After the disaster, where are people defecating? (mark &apos;v&apos; in the appropriate boxes).
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two toilet compartment / toilet of the household.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish ponds, rivers and streams.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilet of the village / hamlet.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields, garden / shrubs.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septic taps / household toilets.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Do people have clean water and soap to wash their hands after using the toilet?.
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c. Raising cattle and poultry.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. What is the local toilet / toilet type?.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13. What are the common types of materials for local toilets / toilets?.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14. What support / toilets have been or will be available?.
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15. How do households treat waste? (mark &apos;v&apos; in the appropriate boxes).
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning.
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect garbage concentrate.
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bury.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (specify).
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (if yes, determine which type of market / store people can buy food) (mark &apos;v&apos; in the appropriate boxes).
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happened. If it happened, how long did it take you to sell it back?.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f. Business.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17. The following functional systems are operating (marking &apos;v&apos; in the appropriate boxes)..
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a. Health facilities (hospitals, clinics, health stations, stations, first aid points).
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b. Transport.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c. Roads (accessibility of affected sites).
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional observations / findings:.
        /// </summary>
        internal static string Table1 {
            get {
                return ResourceManager.GetString("Table1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information needed:.
        /// </summary>
        internal static string Table2 {
            get {
                return ResourceManager.GetString("Table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Notes:.
        /// </summary>
        internal static string Table3 {
            get {
                return ResourceManager.GetString("Table3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
